apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: demo-nfs-storage
  namespace: nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.6
  share: /
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1